import Head from 'next/head'
import HomePage from './Home'


 const Home = () => {
  
  return (
    <div className="border-4 ">
      <Head>
        <title>Web-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <HomePage />
  

    </div>
  )

}

export default Home;