import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Web-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <div>
       <header>
         <h2>TRANSACTIONS</h2>
        
            <Link href='/transactions'><a>New Transactions</a></Link>
         
       </header> 
     </div>
    </div>
  )
}
